set_property PACKAGE_PIN H30 [get_ports {sys_clk_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sys_clk_in[0]}]
set_property PACKAGE_PIN AJ29 [get_ports {pcie_rst_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pcie_rst_n[0]}]
set_property PULLUP true [get_ports {pcie_rst_n[0]}]
set_property PACKAGE_PIN AK29 [get_ports {pcie_wake_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pcie_wake_n[0]}]
set_property PACKAGE_PIN AN10 [get_ports {pcie_clkp[0]}]

set_property PACKAGE_PIN BA29 [get_ports {spi_sel_n[0]}]
set_property PACKAGE_PIN BC27 [get_ports {spi_dqo[0]}]
set_property PACKAGE_PIN BD27 [get_ports {spi_dqi[0]}]
set_property PACKAGE_PIN BD29 [get_ports {spi_hold_n[0]}]
set_property PACKAGE_PIN BD30 [get_ports {spi_wrn_vpp[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_dqi[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_dqo[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_hold_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_sel_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_wrn_vpp[0]}]

create_clock -period 10.000 -name pcie_clkp [get_ports {pcie_clkp[0]}]
#create_clock -period 50.000 -name {sys_clk_in[0]} -waveform {0.000 25.000} [get_ports {sys_clk_in[0]}]
create_clock -period 40.000 -name {sys_clk_in[0]} -waveform {0.000 20.000} [get_ports {sys_clk_in[0]}]
#system clock 
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT4]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT4]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]]
set_false_path -from [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]]
#->u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT2]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT4]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]]

set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT2]]
set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT4]]
set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_clk_rst/u_mysys_clk/inst/mmcm_adv_inst/CLKOUT5]]
#clk_125mhz_mux_->
set_false_path -from [get_clocks clk_125mhz_mux_x0y0] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT0]]
set_false_path -from [get_clocks clk_125mhz_mux_x0y0] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks clk_250mhz_mux_x0y0] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT0]]
set_false_path -from [get_clocks clk_250mhz_mux_x0y0] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
#->clk_125mhz_mux_
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT0]] -to [get_clocks clk_125mhz_mux_x0y0]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT0]] -to [get_clocks clk_250mhz_mux_x0y0]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks clk_125mhz_mux_x0y0]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks clk_250mhz_mux_x0y0]
#ddr<->pcie
#set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_ddr3_cbb/u_ddr3_core/u_ddr3_core_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT3]] -to [get_clocks -of_objects [get_pins u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT2]]

create_property TX_MARGIN_FULL_0 cell -type string
create_property TX_MARGIN_FULL_1 cell -type string
create_property TX_MARGIN_FULL_2 cell -type string
create_property TX_MARGIN_FULL_3 cell -type string
create_property TX_MARGIN_FULL_4 cell -type string
create_property TX_MARGIN_LOW_0 cell -type string
create_property TX_MARGIN_LOW_1 cell -type string
create_property TX_MARGIN_LOW_2 cell -type string
create_property TX_MARGIN_LOW_3 cell -type string
create_property TX_MARGIN_LOW_4 cell -type string
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_RXDETECT_REF 3'b001 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_FULL_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_0 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_1 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_2 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_3 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]
set_property TX_MARGIN_LOW_4 7'b1001010 [get_cells {u_pcie_cbb/u_pcie_core/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gth_channel.gthe2_channel_i}]

set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 32'h00989680 [current_design]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets usr_synclk]
